//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LFTZ_InvestorPortalEntities : DbContext
    {
        public LFTZ_InvestorPortalEntities()
            : base("name=LFTZ_InvestorPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<M_Campaign> M_Campaign { get; set; }
        public virtual DbSet<M_CategorySubCategory> M_CategorySubCategory { get; set; }
        public virtual DbSet<M_Department> M_Department { get; set; }
        public virtual DbSet<M_EnterpriseUser> M_EnterpriseUser { get; set; }
        public virtual DbSet<M_ListOfValues> M_ListOfValues { get; set; }
        public virtual DbSet<M_ListOfValues_RTD> M_ListOfValues_RTD { get; set; }
        public virtual DbSet<M_MobileLog> M_MobileLog { get; set; }
        public virtual DbSet<M_Modules> M_Modules { get; set; }
        public virtual DbSet<M_Question> M_Question { get; set; }
        public virtual DbSet<M_QuestionPollOption> M_QuestionPollOption { get; set; }
        public virtual DbSet<M_Request> M_Request { get; set; }
        public virtual DbSet<M_Role> M_Role { get; set; }
        public virtual DbSet<M_Survey> M_Survey { get; set; }
        public virtual DbSet<M_WarehouseBooking> M_WarehouseBooking { get; set; }
        public virtual DbSet<M_Year> M_Year { get; set; }
        public virtual DbSet<MAP_DepartmentCategory> MAP_DepartmentCategory { get; set; }
        public virtual DbSet<Map_Request> Map_Request { get; set; }
        public virtual DbSet<Map_Warehousebooking> Map_Warehousebooking { get; set; }
        public virtual DbSet<NotifyAlert> NotifyAlerts { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<RefreshToken_Mobile> RefreshToken_Mobile { get; set; }
        public virtual DbSet<Request_Uploads> Request_Uploads { get; set; }
        public virtual DbSet<T_SurveyStatus> T_SurveyStatus { get; set; }
        public virtual DbSet<T_SurveyTransHistory> T_SurveyTransHistory { get; set; }
        public virtual DbSet<T_UserSurveyAnswer> T_UserSurveyAnswer { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<M_FoodDetails_RTD> M_FoodDetails_RTD { get; set; }
        public virtual DbSet<M_MeterDetails_RTD> M_MeterDetails_RTD { get; set; }
        public virtual DbSet<M_Weeks> M_Weeks { get; set; }
        public virtual DbSet<Map_FlatsDetails> Map_FlatsDetails { get; set; }
        public virtual DbSet<Map_Request_history> Map_Request_history { get; set; }
        public virtual DbSet<Map_RequestFeedback> Map_RequestFeedback { get; set; }
        public virtual DbSet<Map_RoleModule> Map_RoleModule { get; set; }
        public virtual DbSet<Map_UserDepartment> Map_UserDepartment { get; set; }
        public virtual DbSet<Map_UserRole> Map_UserRole { get; set; }
    
        public virtual int AddEnterprise_CRUD(string organizationName, ObjectParameter outError)
        {
            var organizationNameParameter = organizationName != null ?
                new ObjectParameter("OrganizationName", organizationName) :
                new ObjectParameter("OrganizationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddEnterprise_CRUD", organizationNameParameter, outError);
        }
    
        public virtual int AdminRequestAllocation_CRUD(Nullable<int> requestId, Nullable<int> departmentID, Nullable<int> priorityID, string requestComments, Nullable<System.DateTime> commitementdate, Nullable<System.DateTime> escalateOndate, string escLevel1EmailId, string uploadPath, Nullable<int> createdBy, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter outError)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(int));
    
            var priorityIDParameter = priorityID.HasValue ?
                new ObjectParameter("PriorityID", priorityID) :
                new ObjectParameter("PriorityID", typeof(int));
    
            var requestCommentsParameter = requestComments != null ?
                new ObjectParameter("RequestComments", requestComments) :
                new ObjectParameter("RequestComments", typeof(string));
    
            var commitementdateParameter = commitementdate.HasValue ?
                new ObjectParameter("Commitementdate", commitementdate) :
                new ObjectParameter("Commitementdate", typeof(System.DateTime));
    
            var escalateOndateParameter = escalateOndate.HasValue ?
                new ObjectParameter("EscalateOndate", escalateOndate) :
                new ObjectParameter("EscalateOndate", typeof(System.DateTime));
    
            var escLevel1EmailIdParameter = escLevel1EmailId != null ?
                new ObjectParameter("EscLevel1EmailId", escLevel1EmailId) :
                new ObjectParameter("EscLevel1EmailId", typeof(string));
    
            var uploadPathParameter = uploadPath != null ?
                new ObjectParameter("UploadPath", uploadPath) :
                new ObjectParameter("UploadPath", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdminRequestAllocation_CRUD", requestIdParameter, departmentIDParameter, priorityIDParameter, requestCommentsParameter, commitementdateParameter, escalateOndateParameter, escLevel1EmailIdParameter, uploadPathParameter, createdByParameter, isActiveParameter, flagParameter, outError);
        }
    
        public virtual ObjectResult<AllEnterpriseWarehouse_G_Result> AllEnterpriseWarehouse_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllEnterpriseWarehouse_G_Result>("AllEnterpriseWarehouse_G");
        }
    
        public virtual int AllocateRequest_CRUD(Nullable<int> allocationID, Nullable<int> uDID, ObjectParameter outError)
        {
            var allocationIDParameter = allocationID.HasValue ?
                new ObjectParameter("AllocationID", allocationID) :
                new ObjectParameter("AllocationID", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AllocateRequest_CRUD", allocationIDParameter, uDIDParameter, outError);
        }
    
        public virtual ObjectResult<AllocateSurvey_CRUD_Result> AllocateSurvey_CRUD(Nullable<int> surveyId, Nullable<int> createdBy, Nullable<bool> isActive)
        {
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllocateSurvey_CRUD_Result>("AllocateSurvey_CRUD", surveyIdParameter, createdByParameter, isActiveParameter);
        }
    
        public virtual int AllocateTicketToTeam_CRUD(Nullable<int> allocationID, Nullable<int> uDID, Nullable<int> createdBy, Nullable<byte> flag, ObjectParameter outError)
        {
            var allocationIDParameter = allocationID.HasValue ?
                new ObjectParameter("AllocationID", allocationID) :
                new ObjectParameter("AllocationID", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AllocateTicketToTeam_CRUD", allocationIDParameter, uDIDParameter, createdByParameter, flagParameter, outError);
        }
    
        public virtual int APILOG_Mobile(string aPIName, string aPIAction, string aPIData)
        {
            var aPINameParameter = aPIName != null ?
                new ObjectParameter("APIName", aPIName) :
                new ObjectParameter("APIName", typeof(string));
    
            var aPIActionParameter = aPIAction != null ?
                new ObjectParameter("APIAction", aPIAction) :
                new ObjectParameter("APIAction", typeof(string));
    
            var aPIDataParameter = aPIData != null ?
                new ObjectParameter("APIData", aPIData) :
                new ObjectParameter("APIData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("APILOG_Mobile", aPINameParameter, aPIActionParameter, aPIDataParameter);
        }
    
        public virtual ObjectResult<AssigneeMailDetail_G_Result> AssigneeMailDetail_G(Nullable<int> surveyId, string assignMemberIds)
        {
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            var assignMemberIdsParameter = assignMemberIds != null ?
                new ObjectParameter("AssignMemberIds", assignMemberIds) :
                new ObjectParameter("AssignMemberIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AssigneeMailDetail_G_Result>("AssigneeMailDetail_G", surveyIdParameter, assignMemberIdsParameter);
        }
    
        public virtual int AssignSurvey_CRUD(Nullable<int> assignSurveyId, Nullable<int> surveyId, string assignMemberIds, Nullable<int> surveyAmount, Nullable<int> surveyStatus, Nullable<int> paymentStatus, Nullable<int> current_User, Nullable<int> flag, ObjectParameter outError)
        {
            var assignSurveyIdParameter = assignSurveyId.HasValue ?
                new ObjectParameter("AssignSurveyId", assignSurveyId) :
                new ObjectParameter("AssignSurveyId", typeof(int));
    
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            var assignMemberIdsParameter = assignMemberIds != null ?
                new ObjectParameter("AssignMemberIds", assignMemberIds) :
                new ObjectParameter("AssignMemberIds", typeof(string));
    
            var surveyAmountParameter = surveyAmount.HasValue ?
                new ObjectParameter("SurveyAmount", surveyAmount) :
                new ObjectParameter("SurveyAmount", typeof(int));
    
            var surveyStatusParameter = surveyStatus.HasValue ?
                new ObjectParameter("SurveyStatus", surveyStatus) :
                new ObjectParameter("SurveyStatus", typeof(int));
    
            var paymentStatusParameter = paymentStatus.HasValue ?
                new ObjectParameter("PaymentStatus", paymentStatus) :
                new ObjectParameter("PaymentStatus", typeof(int));
    
            var current_UserParameter = current_User.HasValue ?
                new ObjectParameter("Current_User", current_User) :
                new ObjectParameter("Current_User", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AssignSurvey_CRUD", assignSurveyIdParameter, surveyIdParameter, assignMemberIdsParameter, surveyAmountParameter, surveyStatusParameter, paymentStatusParameter, current_UserParameter, flagParameter, outError);
        }
    
        public virtual int AssignSurvey_D(Nullable<int> assignSurveyId, ObjectParameter outError)
        {
            var assignSurveyIdParameter = assignSurveyId.HasValue ?
                new ObjectParameter("AssignSurveyId", assignSurveyId) :
                new ObjectParameter("AssignSurveyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AssignSurvey_D", assignSurveyIdParameter, outError);
        }
    
        public virtual ObjectResult<AssignSurvey_G_Result> AssignSurvey_G(Nullable<int> surveyId)
        {
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AssignSurvey_G_Result>("AssignSurvey_G", surveyIdParameter);
        }
    
        public virtual ObjectResult<BookedWarehouse_G_Result> BookedWarehouse_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BookedWarehouse_G_Result>("BookedWarehouse_G");
        }
    
        public virtual ObjectResult<BookedWarehouseById_G_Result> BookedWarehouseById_G(Nullable<int> enterpriseId)
        {
            var enterpriseIdParameter = enterpriseId.HasValue ?
                new ObjectParameter("EnterpriseId", enterpriseId) :
                new ObjectParameter("EnterpriseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BookedWarehouseById_G_Result>("BookedWarehouseById_G", enterpriseIdParameter);
        }
    
        public virtual int Campaign_CRUD(Nullable<int> campaignId, string campaignName, Nullable<int> current_User, Nullable<int> flag, ObjectParameter outError)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(int));
    
            var campaignNameParameter = campaignName != null ?
                new ObjectParameter("CampaignName", campaignName) :
                new ObjectParameter("CampaignName", typeof(string));
    
            var current_UserParameter = current_User.HasValue ?
                new ObjectParameter("Current_User", current_User) :
                new ObjectParameter("Current_User", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Campaign_CRUD", campaignIdParameter, campaignNameParameter, current_UserParameter, flagParameter, outError);
        }
    
        public virtual int Campaign_D(Nullable<int> campaignId, ObjectParameter outError)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Campaign_D", campaignIdParameter, outError);
        }
    
        public virtual int ChangeTicketStatus_CRUD(Nullable<int> allocationID, Nullable<int> requestStatusID, string requestComments, string uploadPath, Nullable<int> createdBy, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter outError)
        {
            var allocationIDParameter = allocationID.HasValue ?
                new ObjectParameter("AllocationID", allocationID) :
                new ObjectParameter("AllocationID", typeof(int));
    
            var requestStatusIDParameter = requestStatusID.HasValue ?
                new ObjectParameter("RequestStatusID", requestStatusID) :
                new ObjectParameter("RequestStatusID", typeof(int));
    
            var requestCommentsParameter = requestComments != null ?
                new ObjectParameter("RequestComments", requestComments) :
                new ObjectParameter("RequestComments", typeof(string));
    
            var uploadPathParameter = uploadPath != null ?
                new ObjectParameter("UploadPath", uploadPath) :
                new ObjectParameter("UploadPath", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeTicketStatus_CRUD", allocationIDParameter, requestStatusIDParameter, requestCommentsParameter, uploadPathParameter, createdByParameter, isActiveParameter, flagParameter, outError);
        }
    
        public virtual ObjectResult<CheckUser_Result> CheckUser(string emailId)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckUser_Result>("CheckUser", emailIdParameter);
        }
    
        public virtual ObjectResult<ConfirmEnterpriseWarehouse_G_Result> ConfirmEnterpriseWarehouse_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConfirmEnterpriseWarehouse_G_Result>("ConfirmEnterpriseWarehouse_G");
        }
    
        public virtual int ConfirmWarehouse_U(Nullable<int> bookingId, Nullable<int> createdBy, ObjectParameter outError, string approverDescription)
        {
            var bookingIdParameter = bookingId.HasValue ?
                new ObjectParameter("BookingId", bookingId) :
                new ObjectParameter("BookingId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var approverDescriptionParameter = approverDescription != null ?
                new ObjectParameter("ApproverDescription", approverDescription) :
                new ObjectParameter("ApproverDescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfirmWarehouse_U", bookingIdParameter, createdByParameter, outError, approverDescriptionParameter);
        }
    
        public virtual ObjectResult<Dashboard_Result> Dashboard(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dashboard_Result>("Dashboard", uDIDParameter);
        }
    
        public virtual int Department_CRUD(Nullable<int> departmentId, string departmentName, string departmentEmailId, string escalationEmailLevel1, Nullable<int> noOfDaysForEscalation, Nullable<int> createdBy, Nullable<int> flag, ObjectParameter outError)
        {
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var departmentNameParameter = departmentName != null ?
                new ObjectParameter("DepartmentName", departmentName) :
                new ObjectParameter("DepartmentName", typeof(string));
    
            var departmentEmailIdParameter = departmentEmailId != null ?
                new ObjectParameter("DepartmentEmailId", departmentEmailId) :
                new ObjectParameter("DepartmentEmailId", typeof(string));
    
            var escalationEmailLevel1Parameter = escalationEmailLevel1 != null ?
                new ObjectParameter("EscalationEmailLevel1", escalationEmailLevel1) :
                new ObjectParameter("EscalationEmailLevel1", typeof(string));
    
            var noOfDaysForEscalationParameter = noOfDaysForEscalation.HasValue ?
                new ObjectParameter("NoOfDaysForEscalation", noOfDaysForEscalation) :
                new ObjectParameter("NoOfDaysForEscalation", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Department_CRUD", departmentIdParameter, departmentNameParameter, departmentEmailIdParameter, escalationEmailLevel1Parameter, noOfDaysForEscalationParameter, createdByParameter, flagParameter, outError);
        }
    
        public virtual int Department_D(Nullable<int> departmentId, ObjectParameter outError)
        {
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Department_D", departmentIdParameter, outError);
        }
    
        public virtual ObjectResult<Department_HODTicketList_G_Result> Department_HODTicketList_G(Nullable<int> departmentID)
        {
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Department_HODTicketList_G_Result>("Department_HODTicketList_G", departmentIDParameter);
        }
    
        public virtual ObjectResult<DepartmentEscalationEmailId_G_Result> DepartmentEscalationEmailId_G(Nullable<int> departmentId)
        {
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DepartmentEscalationEmailId_G_Result>("DepartmentEscalationEmailId_G", departmentIdParameter);
        }
    
        public virtual ObjectResult<DepartmentTicketList_G_Result> DepartmentTicketList_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DepartmentTicketList_G_Result>("DepartmentTicketList_G", uDIDParameter);
        }
    
        public virtual ObjectResult<EnterpriseRole_G_Result> EnterpriseRole_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnterpriseRole_G_Result>("EnterpriseRole_G");
        }
    
        public virtual int EnterpriseUserCreation_CRUD(Nullable<int> udid, Nullable<int> organizationID, string employeeName, string password, Nullable<int> roleId, string emailId, string mobileNo, Nullable<int> createdBy, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter outError, string saltKey)
        {
            var udidParameter = udid.HasValue ?
                new ObjectParameter("udid", udid) :
                new ObjectParameter("udid", typeof(int));
    
            var organizationIDParameter = organizationID.HasValue ?
                new ObjectParameter("OrganizationID", organizationID) :
                new ObjectParameter("OrganizationID", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            var saltKeyParameter = saltKey != null ?
                new ObjectParameter("SaltKey", saltKey) :
                new ObjectParameter("SaltKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnterpriseUserCreation_CRUD", udidParameter, organizationIDParameter, employeeNameParameter, passwordParameter, roleIdParameter, emailIdParameter, mobileNoParameter, createdByParameter, isActiveParameter, flagParameter, outError, saltKeyParameter);
        }
    
        public virtual ObjectResult<EnterpriseUserCreation_G_Result> EnterpriseUserCreation_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnterpriseUserCreation_G_Result>("EnterpriseUserCreation_G", uDIDParameter);
        }
    
        public virtual ObjectResult<EnterpriseUserCreationList_G_Result> EnterpriseUserCreationList_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnterpriseUserCreationList_G_Result>("EnterpriseUserCreationList_G");
        }
    
        public virtual int EnterpriseUserCreationProfile_U(Nullable<int> udid, string profileImagePath, ObjectParameter outError)
        {
            var udidParameter = udid.HasValue ?
                new ObjectParameter("udid", udid) :
                new ObjectParameter("udid", typeof(int));
    
            var profileImagePathParameter = profileImagePath != null ?
                new ObjectParameter("ProfileImagePath", profileImagePath) :
                new ObjectParameter("ProfileImagePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnterpriseUserCreationProfile_U", udidParameter, profileImagePathParameter, outError);
        }
    
        public virtual ObjectResult<EnterpriseUserList_G_Result> EnterpriseUserList_G(Nullable<int> organizationID)
        {
            var organizationIDParameter = organizationID.HasValue ?
                new ObjectParameter("OrganizationID", organizationID) :
                new ObjectParameter("OrganizationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnterpriseUserList_G_Result>("EnterpriseUserList_G", organizationIDParameter);
        }
    
        public virtual int File_d(string uploadFilePath, Nullable<int> udid, ObjectParameter outError)
        {
            var uploadFilePathParameter = uploadFilePath != null ?
                new ObjectParameter("UploadFilePath", uploadFilePath) :
                new ObjectParameter("UploadFilePath", typeof(string));
    
            var udidParameter = udid.HasValue ?
                new ObjectParameter("Udid", udid) :
                new ObjectParameter("Udid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("File_d", uploadFilePathParameter, udidParameter, outError);
        }
    
        public virtual ObjectResult<GetMappingModulesByRoleId_Result> GetMappingModulesByRoleId(Nullable<int> roleid)
        {
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("Roleid", roleid) :
                new ObjectParameter("Roleid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMappingModulesByRoleId_Result>("GetMappingModulesByRoleId", roleidParameter);
        }
    
        public virtual ObjectResult<GetMenusBasedRoleById_G_Result> GetMenusBasedRoleById_G(Nullable<int> udid)
        {
            var udidParameter = udid.HasValue ?
                new ObjectParameter("udid", udid) :
                new ObjectParameter("udid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMenusBasedRoleById_G_Result>("GetMenusBasedRoleById_G", udidParameter);
        }
    
        public virtual ObjectResult<M_CurrentWeeks_G_Result> M_CurrentWeeks_G(Nullable<System.DateTime> currentdate)
        {
            var currentdateParameter = currentdate.HasValue ?
                new ObjectParameter("Currentdate", currentdate) :
                new ObjectParameter("Currentdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_CurrentWeeks_G_Result>("M_CurrentWeeks_G", currentdateParameter);
        }
    
        public virtual ObjectResult<M_ListOfDepartment_G_Result> M_ListOfDepartment_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_ListOfDepartment_G_Result>("M_ListOfDepartment_G", uDIDParameter);
        }
    
        public virtual ObjectResult<M_ListOfEnterprise_G_Result> M_ListOfEnterprise_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_ListOfEnterprise_G_Result>("M_ListOfEnterprise_G", uDIDParameter);
        }
    
        public virtual ObjectResult<M_LOC_G_Result> M_LOC_G(Nullable<int> requestTypeId)
        {
            var requestTypeIdParameter = requestTypeId.HasValue ?
                new ObjectParameter("RequestTypeId", requestTypeId) :
                new ObjectParameter("RequestTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_LOC_G_Result>("M_LOC_G", requestTypeIdParameter);
        }
    
        public virtual ObjectResult<M_LOC_Sub_G_Result> M_LOC_Sub_G(Nullable<int> categoryID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_LOC_Sub_G_Result>("M_LOC_Sub_G", categoryIDParameter);
        }
    
        public virtual ObjectResult<M_LOV_G_Result> M_LOV_G(Nullable<int> lOVId)
        {
            var lOVIdParameter = lOVId.HasValue ?
                new ObjectParameter("LOVId", lOVId) :
                new ObjectParameter("LOVId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_LOV_G_Result>("M_LOV_G", lOVIdParameter);
        }
    
        public virtual ObjectResult<M_LOV_RTD_G_Result> M_LOV_RTD_G(Nullable<int> lOVId)
        {
            var lOVIdParameter = lOVId.HasValue ?
                new ObjectParameter("LOVId", lOVId) :
                new ObjectParameter("LOVId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_LOV_RTD_G_Result>("M_LOV_RTD_G", lOVIdParameter);
        }
    
        public virtual ObjectResult<M_Organization_G_Result> M_Organization_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_Organization_G_Result>("M_Organization_G");
        }
    
        public virtual ObjectResult<M_UserDepartmentList_G_Result> M_UserDepartmentList_G(Nullable<int> departmentID, Nullable<int> uDID)
        {
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_UserDepartmentList_G_Result>("M_UserDepartmentList_G", departmentIDParameter, uDIDParameter);
        }
    
        public virtual ObjectResult<M_UserDepartmentMappedList_G_Result> M_UserDepartmentMappedList_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_UserDepartmentMappedList_G_Result>("M_UserDepartmentMappedList_G", uDIDParameter);
        }
    
        public virtual ObjectResult<M_UserDetails_G_Result> M_UserDetails_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_UserDetails_G_Result>("M_UserDetails_G");
        }
    
        public virtual ObjectResult<M_WeeksDetails_G_Result> M_WeeksDetails_G(Nullable<int> weekId)
        {
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("weekId", weekId) :
                new ObjectParameter("weekId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_WeeksDetails_G_Result>("M_WeeksDetails_G", weekIdParameter);
        }
    
        public virtual ObjectResult<MeterDetailsEdit_G_Result> MeterDetailsEdit_G(Nullable<int> mId)
        {
            var mIdParameter = mId.HasValue ?
                new ObjectParameter("MId", mId) :
                new ObjectParameter("MId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MeterDetailsEdit_G_Result>("MeterDetailsEdit_G", mIdParameter);
        }
    
        public virtual ObjectResult<MeterDetailsList_G_Result> MeterDetailsList_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MeterDetailsList_G_Result>("MeterDetailsList_G");
        }
    
        public virtual int MeterDetailsRTD_CRUD(Nullable<int> mId, Nullable<int> yearId, Nullable<int> monthId, Nullable<int> categoryId, Nullable<int> subcategoryId, Nullable<decimal> meterReading, Nullable<int> createdBy, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter outError)
        {
            var mIdParameter = mId.HasValue ?
                new ObjectParameter("MId", mId) :
                new ObjectParameter("MId", typeof(int));
    
            var yearIdParameter = yearId.HasValue ?
                new ObjectParameter("YearId", yearId) :
                new ObjectParameter("YearId", typeof(int));
    
            var monthIdParameter = monthId.HasValue ?
                new ObjectParameter("MonthId", monthId) :
                new ObjectParameter("MonthId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var subcategoryIdParameter = subcategoryId.HasValue ?
                new ObjectParameter("SubcategoryId", subcategoryId) :
                new ObjectParameter("SubcategoryId", typeof(int));
    
            var meterReadingParameter = meterReading.HasValue ?
                new ObjectParameter("MeterReading", meterReading) :
                new ObjectParameter("MeterReading", typeof(decimal));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MeterDetailsRTD_CRUD", mIdParameter, yearIdParameter, monthIdParameter, categoryIdParameter, subcategoryIdParameter, meterReadingParameter, createdByParameter, isActiveParameter, flagParameter, outError);
        }
    
        public virtual ObjectResult<MeterDetailsView_G_Result> MeterDetailsView_G(Nullable<int> udid)
        {
            var udidParameter = udid.HasValue ?
                new ObjectParameter("udid", udid) :
                new ObjectParameter("udid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MeterDetailsView_G_Result>("MeterDetailsView_G", udidParameter);
        }
    
        public virtual ObjectResult<MyTicketList_G_Result> MyTicketList_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MyTicketList_G_Result>("MyTicketList_G", uDIDParameter);
        }
    
        public virtual int Question_CRUD(Nullable<int> questionId, Nullable<int> surveyId, string question, Nullable<int> displayOnPageNo, Nullable<int> questionTypeId, Nullable<int> current_User, Nullable<int> flag, ObjectParameter outError, ObjectParameter outQuestionId)
        {
            var questionIdParameter = questionId.HasValue ?
                new ObjectParameter("QuestionId", questionId) :
                new ObjectParameter("QuestionId", typeof(int));
    
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            var questionParameter = question != null ?
                new ObjectParameter("Question", question) :
                new ObjectParameter("Question", typeof(string));
    
            var displayOnPageNoParameter = displayOnPageNo.HasValue ?
                new ObjectParameter("DisplayOnPageNo", displayOnPageNo) :
                new ObjectParameter("DisplayOnPageNo", typeof(int));
    
            var questionTypeIdParameter = questionTypeId.HasValue ?
                new ObjectParameter("QuestionTypeId", questionTypeId) :
                new ObjectParameter("QuestionTypeId", typeof(int));
    
            var current_UserParameter = current_User.HasValue ?
                new ObjectParameter("Current_User", current_User) :
                new ObjectParameter("Current_User", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Question_CRUD", questionIdParameter, surveyIdParameter, questionParameter, displayOnPageNoParameter, questionTypeIdParameter, current_UserParameter, flagParameter, outError, outQuestionId);
        }
    
        public virtual int Question_D(Nullable<int> questionId, ObjectParameter outError)
        {
            var questionIdParameter = questionId.HasValue ?
                new ObjectParameter("QuestionId", questionId) :
                new ObjectParameter("QuestionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Question_D", questionIdParameter, outError);
        }
    
        public virtual ObjectResult<Question_G_Result> Question_G(Nullable<int> surveyId)
        {
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Question_G_Result>("Question_G", surveyIdParameter);
        }
    
        public virtual int QuestionPollOption_CRUD(ObjectParameter outError)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QuestionPollOption_CRUD", outError);
        }
    
        public virtual int QuestionPollOption_D(Nullable<int> questionId, ObjectParameter outError)
        {
            var questionIdParameter = questionId.HasValue ?
                new ObjectParameter("QuestionId", questionId) :
                new ObjectParameter("QuestionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QuestionPollOption_D", questionIdParameter, outError);
        }
    
        public virtual ObjectResult<RejectedWarehouse_G_Result> RejectedWarehouse_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RejectedWarehouse_G_Result>("RejectedWarehouse_G");
        }
    
        public virtual ObjectResult<RejectedWarehouseById_Result> RejectedWarehouseById(Nullable<int> enterpriseId)
        {
            var enterpriseIdParameter = enterpriseId.HasValue ?
                new ObjectParameter("EnterpriseId", enterpriseId) :
                new ObjectParameter("EnterpriseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RejectedWarehouseById_Result>("RejectedWarehouseById", enterpriseIdParameter);
        }
    
        public virtual int RejectWarehouse_U(Nullable<int> bookingId, Nullable<int> createdBy, ObjectParameter outError, string approverDescription)
        {
            var bookingIdParameter = bookingId.HasValue ?
                new ObjectParameter("BookingId", bookingId) :
                new ObjectParameter("BookingId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var approverDescriptionParameter = approverDescription != null ?
                new ObjectParameter("ApproverDescription", approverDescription) :
                new ObjectParameter("ApproverDescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RejectWarehouse_U", bookingIdParameter, createdByParameter, outError, approverDescriptionParameter);
        }
    
        public virtual int ReopenRequest_U(Nullable<int> requestId, Nullable<int> requestStatusID, string reOpenedComments, Nullable<int> uDID, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter outError)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            var requestStatusIDParameter = requestStatusID.HasValue ?
                new ObjectParameter("RequestStatusID", requestStatusID) :
                new ObjectParameter("RequestStatusID", typeof(int));
    
            var reOpenedCommentsParameter = reOpenedComments != null ?
                new ObjectParameter("ReOpenedComments", reOpenedComments) :
                new ObjectParameter("ReOpenedComments", typeof(string));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReopenRequest_U", requestIdParameter, requestStatusIDParameter, reOpenedCommentsParameter, uDIDParameter, isActiveParameter, flagParameter, outError);
        }
    
        public virtual ObjectResult<Request_Email_ChangeTicketStatus_G_Result> Request_Email_ChangeTicketStatus_G(Nullable<int> allocationId)
        {
            var allocationIdParameter = allocationId.HasValue ?
                new ObjectParameter("AllocationId", allocationId) :
                new ObjectParameter("AllocationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Request_Email_ChangeTicketStatus_G_Result>("Request_Email_ChangeTicketStatus_G", allocationIdParameter);
        }
    
        public virtual ObjectResult<Request_Email_Enterprise_G_Result> Request_Email_Enterprise_G(Nullable<int> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Request_Email_Enterprise_G_Result>("Request_Email_Enterprise_G", requestIdParameter);
        }
    
        public virtual ObjectResult<Request_Email_Escalation_G_Result> Request_Email_Escalation_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Request_Email_Escalation_G_Result>("Request_Email_Escalation_G");
        }
    
        public virtual ObjectResult<Request_Email_HODTicketAssign_G_Result> Request_Email_HODTicketAssign_G(Nullable<int> allocationId)
        {
            var allocationIdParameter = allocationId.HasValue ?
                new ObjectParameter("AllocationId", allocationId) :
                new ObjectParameter("AllocationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Request_Email_HODTicketAssign_G_Result>("Request_Email_HODTicketAssign_G", allocationIdParameter);
        }
    
        public virtual ObjectResult<Request_Email_ReopenedDetails_G_Result> Request_Email_ReopenedDetails_G(Nullable<int> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Request_Email_ReopenedDetails_G_Result>("Request_Email_ReopenedDetails_G", requestIdParameter);
        }
    
        public virtual ObjectResult<string> RequestedWarehouse_G(Nullable<int> bookingId)
        {
            var bookingIdParameter = bookingId.HasValue ?
                new ObjectParameter("BookingId", bookingId) :
                new ObjectParameter("BookingId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("RequestedWarehouse_G", bookingIdParameter);
        }
    
        public virtual int RequestFeedBackRating_CRUD(Nullable<int> requestId, Nullable<int> ratingID, string feedbackComments, Nullable<int> createdBy, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter outError)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            var ratingIDParameter = ratingID.HasValue ?
                new ObjectParameter("RatingID", ratingID) :
                new ObjectParameter("RatingID", typeof(int));
    
            var feedbackCommentsParameter = feedbackComments != null ?
                new ObjectParameter("FeedbackComments", feedbackComments) :
                new ObjectParameter("FeedbackComments", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RequestFeedBackRating_CRUD", requestIdParameter, ratingIDParameter, feedbackCommentsParameter, createdByParameter, isActiveParameter, flagParameter, outError);
        }
    
        public virtual int RequestForm_D(Nullable<int> requestId, Nullable<int> uDID, ObjectParameter outError)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RequestForm_D", requestIdParameter, uDIDParameter, outError);
        }
    
        public virtual ObjectResult<RequestFormEdit_G_Result> RequestFormEdit_G(Nullable<int> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestFormEdit_G_Result>("RequestFormEdit_G", requestIdParameter);
        }
    
        public virtual ObjectResult<RequestFormEdit_G_Mobile_Result> RequestFormEdit_G_Mobile(Nullable<int> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestFormEdit_G_Mobile_Result>("RequestFormEdit_G_Mobile", requestIdParameter);
        }
    
        public virtual ObjectResult<RequestFormEPUserList_G_Result> RequestFormEPUserList_G(Nullable<int> organizationID)
        {
            var organizationIDParameter = organizationID.HasValue ?
                new ObjectParameter("OrganizationID", organizationID) :
                new ObjectParameter("OrganizationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestFormEPUserList_G_Result>("RequestFormEPUserList_G", organizationIDParameter);
        }
    
        public virtual ObjectResult<RequestFormLFZUserList_G_Result> RequestFormLFZUserList_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestFormLFZUserList_G_Result>("RequestFormLFZUserList_G", uDIDParameter);
        }
    
        public virtual ObjectResult<RequestHistoryList_G_Result> RequestHistoryList_G(Nullable<int> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestHistoryList_G_Result>("RequestHistoryList_G", requestIdParameter);
        }
    
        public virtual ObjectResult<RequestHistoryList_G_old_Result> RequestHistoryList_G_old(Nullable<int> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestHistoryList_G_old_Result>("RequestHistoryList_G_old", requestIdParameter);
        }
    
        public virtual ObjectResult<RequestListAdmin_G_Result> RequestListAdmin_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestListAdmin_G_Result>("RequestListAdmin_G");
        }
    
        public virtual ObjectResult<RequestWorkingListAdmin_G_Result> RequestWorkingListAdmin_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequestWorkingListAdmin_G_Result>("RequestWorkingListAdmin_G", uDIDParameter);
        }
    
        public virtual int RereshToken_Crud_Mobile(string username, string refreshToken)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var refreshTokenParameter = refreshToken != null ?
                new ObjectParameter("RefreshToken", refreshToken) :
                new ObjectParameter("RefreshToken", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RereshToken_Crud_Mobile", usernameParameter, refreshTokenParameter);
        }
    
        public virtual ObjectResult<RereshToken_G_Mobile_Result> RereshToken_G_Mobile(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RereshToken_G_Mobile_Result>("RereshToken_G_Mobile", usernameParameter);
        }
    
        public virtual ObjectResult<Role_G_Result> Role_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Role_G_Result>("Role_G");
        }
    
        [DbFunction("LFTZ_InvestorPortalEntities", "Split")]
        public virtual IQueryable<string> Split(string inputString, string delimiter)
        {
            var inputStringParameter = inputString != null ?
                new ObjectParameter("InputString", inputString) :
                new ObjectParameter("InputString", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[LFTZ_InvestorPortalEntities].[Split](@InputString, @Delimiter)", inputStringParameter, delimiterParameter);
        }
    
        public virtual int Survey_CRUD(Nullable<int> surveyId, Nullable<int> campaignId, string surveyName, Nullable<int> noOfPages, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> status, Nullable<int> current_User, Nullable<int> flag, ObjectParameter outError)
        {
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(int));
    
            var surveyNameParameter = surveyName != null ?
                new ObjectParameter("SurveyName", surveyName) :
                new ObjectParameter("SurveyName", typeof(string));
    
            var noOfPagesParameter = noOfPages.HasValue ?
                new ObjectParameter("NoOfPages", noOfPages) :
                new ObjectParameter("NoOfPages", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var current_UserParameter = current_User.HasValue ?
                new ObjectParameter("Current_User", current_User) :
                new ObjectParameter("Current_User", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Survey_CRUD", surveyIdParameter, campaignIdParameter, surveyNameParameter, noOfPagesParameter, startDateParameter, endDateParameter, statusParameter, current_UserParameter, flagParameter, outError);
        }
    
        public virtual int Survey_D(Nullable<int> surveyId, ObjectParameter outError)
        {
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Survey_D", surveyIdParameter, outError);
        }
    
        public virtual ObjectResult<Survey_G_Result> Survey_G(Nullable<int> campaignId)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Survey_G_Result>("Survey_G", campaignIdParameter);
        }
    
        public virtual ObjectResult<SurveyCompletionMailDetail_G_Result> SurveyCompletionMailDetail_G(Nullable<int> assignSurveyId)
        {
            var assignSurveyIdParameter = assignSurveyId.HasValue ?
                new ObjectParameter("AssignSurveyId", assignSurveyId) :
                new ObjectParameter("AssignSurveyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SurveyCompletionMailDetail_G_Result>("SurveyCompletionMailDetail_G", assignSurveyIdParameter);
        }
    
        public virtual ObjectResult<SurveyDashboard_G_Result> SurveyDashboard_G(Nullable<int> roleId, Nullable<int> uDID)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SurveyDashboard_G_Result>("SurveyDashboard_G", roleIdParameter, uDIDParameter);
        }
    
        public virtual ObjectResult<TOP_3_ComplaintDrivers_Result> TOP_3_ComplaintDrivers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TOP_3_ComplaintDrivers_Result>("TOP_3_ComplaintDrivers");
        }
    
        public virtual ObjectResult<Top_3_ComplaintDrivers_Details_Result> Top_3_ComplaintDrivers_Details(Nullable<int> subCategoryId, Nullable<int> requestId)
        {
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("SubCategoryId", subCategoryId) :
                new ObjectParameter("SubCategoryId", typeof(int));
    
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top_3_ComplaintDrivers_Details_Result>("Top_3_ComplaintDrivers_Details", subCategoryIdParameter, requestIdParameter);
        }
    
        public virtual ObjectResult<TOP3_SLA_Result> TOP3_SLA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TOP3_SLA_Result>("TOP3_SLA");
        }
    
        public virtual int UpdateAssignSurveyStatus_CRUD(Nullable<int> assignSurveyId, string assignSurveyIds, Nullable<int> surveyStatus, Nullable<int> paymentStatus, Nullable<int> current_User, ObjectParameter outError)
        {
            var assignSurveyIdParameter = assignSurveyId.HasValue ?
                new ObjectParameter("AssignSurveyId", assignSurveyId) :
                new ObjectParameter("AssignSurveyId", typeof(int));
    
            var assignSurveyIdsParameter = assignSurveyIds != null ?
                new ObjectParameter("AssignSurveyIds", assignSurveyIds) :
                new ObjectParameter("AssignSurveyIds", typeof(string));
    
            var surveyStatusParameter = surveyStatus.HasValue ?
                new ObjectParameter("SurveyStatus", surveyStatus) :
                new ObjectParameter("SurveyStatus", typeof(int));
    
            var paymentStatusParameter = paymentStatus.HasValue ?
                new ObjectParameter("PaymentStatus", paymentStatus) :
                new ObjectParameter("PaymentStatus", typeof(int));
    
            var current_UserParameter = current_User.HasValue ?
                new ObjectParameter("Current_User", current_User) :
                new ObjectParameter("Current_User", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAssignSurveyStatus_CRUD", assignSurveyIdParameter, assignSurveyIdsParameter, surveyStatusParameter, paymentStatusParameter, current_UserParameter, outError);
        }
    
        public virtual ObjectResult<UserAssignedSurvey_G_Result> UserAssignedSurvey_G(Nullable<int> enterpriseId)
        {
            var enterpriseIdParameter = enterpriseId.HasValue ?
                new ObjectParameter("EnterpriseId", enterpriseId) :
                new ObjectParameter("EnterpriseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserAssignedSurvey_G_Result>("UserAssignedSurvey_G", enterpriseIdParameter);
        }
    
        public virtual int UserChangePassword(Nullable<int> uDID, string password, string saltKey, ObjectParameter outError)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var saltKeyParameter = saltKey != null ?
                new ObjectParameter("SaltKey", saltKey) :
                new ObjectParameter("SaltKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserChangePassword", uDIDParameter, passwordParameter, saltKeyParameter, outError);
        }
    
        public virtual int UserCreation_CRUD(Nullable<int> udid, string employeeName, string password, Nullable<int> roleId, string departmentIds, string emailId, string mobileNo, Nullable<int> createdBy, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter outError, string saltKey)
        {
            var udidParameter = udid.HasValue ?
                new ObjectParameter("udid", udid) :
                new ObjectParameter("udid", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var departmentIdsParameter = departmentIds != null ?
                new ObjectParameter("DepartmentIds", departmentIds) :
                new ObjectParameter("DepartmentIds", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            var saltKeyParameter = saltKey != null ?
                new ObjectParameter("SaltKey", saltKey) :
                new ObjectParameter("SaltKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserCreation_CRUD", udidParameter, employeeNameParameter, passwordParameter, roleIdParameter, departmentIdsParameter, emailIdParameter, mobileNoParameter, createdByParameter, isActiveParameter, flagParameter, outError, saltKeyParameter);
        }
    
        public virtual int UserCreation_D(Nullable<int> uDID, ObjectParameter outError)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserCreation_D", uDIDParameter, outError);
        }
    
        public virtual ObjectResult<UserCreation_G_Result> UserCreation_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserCreation_G_Result>("UserCreation_G", uDIDParameter);
        }
    
        public virtual ObjectResult<UserCreationList_G_Result> UserCreationList_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserCreationList_G_Result>("UserCreationList_G");
        }
    
        public virtual int UserCreationUpdate_Mobile(string employeeName, string emailId, string mobileNo, ObjectParameter outError)
        {
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserCreationUpdate_Mobile", employeeNameParameter, emailIdParameter, mobileNoParameter, outError);
        }
    
        public virtual ObjectResult<Userdetails_G_Result> Userdetails_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Userdetails_G_Result>("Userdetails_G", uDIDParameter);
        }
    
        public virtual ObjectResult<UserDetails_Mobile_Result> UserDetails_Mobile(string emailId)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserDetails_Mobile_Result>("UserDetails_Mobile", emailIdParameter);
        }
    
        public virtual int UserLogin(string emailId, string password, ObjectParameter outError)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserLogin", emailIdParameter, passwordParameter, outError);
        }
    
        public virtual ObjectResult<UserSurvey_QuestionAnswer_G_Result> UserSurvey_QuestionAnswer_G(Nullable<int> surveyId, Nullable<int> createdBy)
        {
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserSurvey_QuestionAnswer_G_Result>("UserSurvey_QuestionAnswer_G", surveyIdParameter, createdByParameter);
        }
    
        public virtual int UserSurveyAnswer_CRUD(Nullable<int> userSurveyAnswerId, Nullable<int> assignSurveyId, Nullable<int> surveyId, Nullable<int> questionId, string answer, string remark, Nullable<int> current_User, Nullable<int> flag, ObjectParameter outError)
        {
            var userSurveyAnswerIdParameter = userSurveyAnswerId.HasValue ?
                new ObjectParameter("UserSurveyAnswerId", userSurveyAnswerId) :
                new ObjectParameter("UserSurveyAnswerId", typeof(int));
    
            var assignSurveyIdParameter = assignSurveyId.HasValue ?
                new ObjectParameter("AssignSurveyId", assignSurveyId) :
                new ObjectParameter("AssignSurveyId", typeof(int));
    
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(int));
    
            var questionIdParameter = questionId.HasValue ?
                new ObjectParameter("QuestionId", questionId) :
                new ObjectParameter("QuestionId", typeof(int));
    
            var answerParameter = answer != null ?
                new ObjectParameter("Answer", answer) :
                new ObjectParameter("Answer", typeof(string));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("Remark", remark) :
                new ObjectParameter("Remark", typeof(string));
    
            var current_UserParameter = current_User.HasValue ?
                new ObjectParameter("Current_User", current_User) :
                new ObjectParameter("Current_User", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserSurveyAnswer_CRUD", userSurveyAnswerIdParameter, assignSurveyIdParameter, surveyIdParameter, questionIdParameter, answerParameter, remarkParameter, current_UserParameter, flagParameter, outError);
        }
    
        public virtual ObjectResult<UserSurveyAnswer_G_Result> UserSurveyAnswer_G(Nullable<int> assignSurveyId, Nullable<int> questionId)
        {
            var assignSurveyIdParameter = assignSurveyId.HasValue ?
                new ObjectParameter("AssignSurveyId", assignSurveyId) :
                new ObjectParameter("AssignSurveyId", typeof(int));
    
            var questionIdParameter = questionId.HasValue ?
                new ObjectParameter("QuestionId", questionId) :
                new ObjectParameter("QuestionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserSurveyAnswer_G_Result>("UserSurveyAnswer_G", assignSurveyIdParameter, questionIdParameter);
        }
    
        public virtual ObjectResult<ValidateUser_OnePortal_Result> ValidateUser_OnePortal(string emailid)
        {
            var emailidParameter = emailid != null ?
                new ObjectParameter("Emailid", emailid) :
                new ObjectParameter("Emailid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidateUser_OnePortal_Result>("ValidateUser_OnePortal", emailidParameter);
        }
    
        public virtual ObjectResult<WarehouseAllPendingRequest_ById_Result> WarehouseAllPendingRequest_ById(Nullable<int> enterpriseId)
        {
            var enterpriseIdParameter = enterpriseId.HasValue ?
                new ObjectParameter("EnterpriseId", enterpriseId) :
                new ObjectParameter("EnterpriseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WarehouseAllPendingRequest_ById_Result>("WarehouseAllPendingRequest_ById", enterpriseIdParameter);
        }
    
        public virtual ObjectResult<WarehouseAllPendingRequest_G_Result> WarehouseAllPendingRequest_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WarehouseAllPendingRequest_G_Result>("WarehouseAllPendingRequest_G");
        }
    
        public virtual int WarehouseBooking_CRUD(Nullable<int> bookingId, Nullable<int> enterpriseId, Nullable<int> categoryId, string sizeRequired, Nullable<System.DateTime> requiredFrom, Nullable<System.DateTime> requiredTo, string warehouseDescription, Nullable<int> createdby, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter outError, string storageTypeId, string storageArea)
        {
            var bookingIdParameter = bookingId.HasValue ?
                new ObjectParameter("BookingId", bookingId) :
                new ObjectParameter("BookingId", typeof(int));
    
            var enterpriseIdParameter = enterpriseId.HasValue ?
                new ObjectParameter("EnterpriseId", enterpriseId) :
                new ObjectParameter("EnterpriseId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var sizeRequiredParameter = sizeRequired != null ?
                new ObjectParameter("SizeRequired", sizeRequired) :
                new ObjectParameter("SizeRequired", typeof(string));
    
            var requiredFromParameter = requiredFrom.HasValue ?
                new ObjectParameter("RequiredFrom", requiredFrom) :
                new ObjectParameter("RequiredFrom", typeof(System.DateTime));
    
            var requiredToParameter = requiredTo.HasValue ?
                new ObjectParameter("RequiredTo", requiredTo) :
                new ObjectParameter("RequiredTo", typeof(System.DateTime));
    
            var warehouseDescriptionParameter = warehouseDescription != null ?
                new ObjectParameter("WarehouseDescription", warehouseDescription) :
                new ObjectParameter("WarehouseDescription", typeof(string));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            var storageTypeIdParameter = storageTypeId != null ?
                new ObjectParameter("StorageTypeId", storageTypeId) :
                new ObjectParameter("StorageTypeId", typeof(string));
    
            var storageAreaParameter = storageArea != null ?
                new ObjectParameter("StorageArea", storageArea) :
                new ObjectParameter("StorageArea", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WarehouseBooking_CRUD", bookingIdParameter, enterpriseIdParameter, categoryIdParameter, sizeRequiredParameter, requiredFromParameter, requiredToParameter, warehouseDescriptionParameter, createdbyParameter, isActiveParameter, flagParameter, outError, storageTypeIdParameter, storageAreaParameter);
        }
    
        public virtual int FoodDetailsRTD_CRUD(Nullable<int> fDId, Nullable<int> year, Nullable<int> weekId, Nullable<System.DateTime> monday_Date, string monday_BF, string monday_L, string monday_D, Nullable<System.DateTime> tuesday_Date, string tuesday_BF, string tuesday_L, string tuesday_D, Nullable<System.DateTime> wednesday_Date, string wednesday_BF, string wednesday_L, string wednesday_D, Nullable<System.DateTime> thursday_Date, string thursday_BF, string thursday_L, string thursday_D, Nullable<System.DateTime> friday_Date, string friday_BF, string friday_L, string friday_D, Nullable<System.DateTime> saturday_Date, string saturday_BF, string saturday_L, string saturday_D, Nullable<System.DateTime> sunday_Date, string sunday_BF, string sunday_L, string sunday_D, Nullable<int> createdBy, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter foodDetailsID, ObjectParameter outError)
        {
            var fDIdParameter = fDId.HasValue ?
                new ObjectParameter("FDId", fDId) :
                new ObjectParameter("FDId", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("WeekId", weekId) :
                new ObjectParameter("WeekId", typeof(int));
    
            var monday_DateParameter = monday_Date.HasValue ?
                new ObjectParameter("Monday_Date", monday_Date) :
                new ObjectParameter("Monday_Date", typeof(System.DateTime));
    
            var monday_BFParameter = monday_BF != null ?
                new ObjectParameter("Monday_BF", monday_BF) :
                new ObjectParameter("Monday_BF", typeof(string));
    
            var monday_LParameter = monday_L != null ?
                new ObjectParameter("Monday_L", monday_L) :
                new ObjectParameter("Monday_L", typeof(string));
    
            var monday_DParameter = monday_D != null ?
                new ObjectParameter("Monday_D", monday_D) :
                new ObjectParameter("Monday_D", typeof(string));
    
            var tuesday_DateParameter = tuesday_Date.HasValue ?
                new ObjectParameter("Tuesday_Date", tuesday_Date) :
                new ObjectParameter("Tuesday_Date", typeof(System.DateTime));
    
            var tuesday_BFParameter = tuesday_BF != null ?
                new ObjectParameter("Tuesday_BF", tuesday_BF) :
                new ObjectParameter("Tuesday_BF", typeof(string));
    
            var tuesday_LParameter = tuesday_L != null ?
                new ObjectParameter("Tuesday_L", tuesday_L) :
                new ObjectParameter("Tuesday_L", typeof(string));
    
            var tuesday_DParameter = tuesday_D != null ?
                new ObjectParameter("Tuesday_D", tuesday_D) :
                new ObjectParameter("Tuesday_D", typeof(string));
    
            var wednesday_DateParameter = wednesday_Date.HasValue ?
                new ObjectParameter("Wednesday_Date", wednesday_Date) :
                new ObjectParameter("Wednesday_Date", typeof(System.DateTime));
    
            var wednesday_BFParameter = wednesday_BF != null ?
                new ObjectParameter("Wednesday_BF", wednesday_BF) :
                new ObjectParameter("Wednesday_BF", typeof(string));
    
            var wednesday_LParameter = wednesday_L != null ?
                new ObjectParameter("Wednesday_L", wednesday_L) :
                new ObjectParameter("Wednesday_L", typeof(string));
    
            var wednesday_DParameter = wednesday_D != null ?
                new ObjectParameter("Wednesday_D", wednesday_D) :
                new ObjectParameter("Wednesday_D", typeof(string));
    
            var thursday_DateParameter = thursday_Date.HasValue ?
                new ObjectParameter("Thursday_Date", thursday_Date) :
                new ObjectParameter("Thursday_Date", typeof(System.DateTime));
    
            var thursday_BFParameter = thursday_BF != null ?
                new ObjectParameter("Thursday_BF", thursday_BF) :
                new ObjectParameter("Thursday_BF", typeof(string));
    
            var thursday_LParameter = thursday_L != null ?
                new ObjectParameter("Thursday_L", thursday_L) :
                new ObjectParameter("Thursday_L", typeof(string));
    
            var thursday_DParameter = thursday_D != null ?
                new ObjectParameter("Thursday_D", thursday_D) :
                new ObjectParameter("Thursday_D", typeof(string));
    
            var friday_DateParameter = friday_Date.HasValue ?
                new ObjectParameter("Friday_Date", friday_Date) :
                new ObjectParameter("Friday_Date", typeof(System.DateTime));
    
            var friday_BFParameter = friday_BF != null ?
                new ObjectParameter("Friday_BF", friday_BF) :
                new ObjectParameter("Friday_BF", typeof(string));
    
            var friday_LParameter = friday_L != null ?
                new ObjectParameter("Friday_L", friday_L) :
                new ObjectParameter("Friday_L", typeof(string));
    
            var friday_DParameter = friday_D != null ?
                new ObjectParameter("Friday_D", friday_D) :
                new ObjectParameter("Friday_D", typeof(string));
    
            var saturday_DateParameter = saturday_Date.HasValue ?
                new ObjectParameter("Saturday_Date", saturday_Date) :
                new ObjectParameter("Saturday_Date", typeof(System.DateTime));
    
            var saturday_BFParameter = saturday_BF != null ?
                new ObjectParameter("Saturday_BF", saturday_BF) :
                new ObjectParameter("Saturday_BF", typeof(string));
    
            var saturday_LParameter = saturday_L != null ?
                new ObjectParameter("Saturday_L", saturday_L) :
                new ObjectParameter("Saturday_L", typeof(string));
    
            var saturday_DParameter = saturday_D != null ?
                new ObjectParameter("Saturday_D", saturday_D) :
                new ObjectParameter("Saturday_D", typeof(string));
    
            var sunday_DateParameter = sunday_Date.HasValue ?
                new ObjectParameter("Sunday_Date", sunday_Date) :
                new ObjectParameter("Sunday_Date", typeof(System.DateTime));
    
            var sunday_BFParameter = sunday_BF != null ?
                new ObjectParameter("Sunday_BF", sunday_BF) :
                new ObjectParameter("Sunday_BF", typeof(string));
    
            var sunday_LParameter = sunday_L != null ?
                new ObjectParameter("Sunday_L", sunday_L) :
                new ObjectParameter("Sunday_L", typeof(string));
    
            var sunday_DParameter = sunday_D != null ?
                new ObjectParameter("Sunday_D", sunday_D) :
                new ObjectParameter("Sunday_D", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FoodDetailsRTD_CRUD", fDIdParameter, yearParameter, weekIdParameter, monday_DateParameter, monday_BFParameter, monday_LParameter, monday_DParameter, tuesday_DateParameter, tuesday_BFParameter, tuesday_LParameter, tuesday_DParameter, wednesday_DateParameter, wednesday_BFParameter, wednesday_LParameter, wednesday_DParameter, thursday_DateParameter, thursday_BFParameter, thursday_LParameter, thursday_DParameter, friday_DateParameter, friday_BFParameter, friday_LParameter, friday_DParameter, saturday_DateParameter, saturday_BFParameter, saturday_LParameter, saturday_DParameter, sunday_DateParameter, sunday_BFParameter, sunday_LParameter, sunday_DParameter, createdByParameter, isActiveParameter, flagParameter, foodDetailsID, outError);
        }
    
        public virtual ObjectResult<M_Year_G_Result> M_Year_G(Nullable<short> flag)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_Year_G_Result>("M_Year_G", flagParameter);
        }
    
        public virtual ObjectResult<FoodDetailsTenantView_G_Result> FoodDetailsTenantView_G(Nullable<System.DateTime> currentdate)
        {
            var currentdateParameter = currentdate.HasValue ?
                new ObjectParameter("Currentdate", currentdate) :
                new ObjectParameter("Currentdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FoodDetailsTenantView_G_Result>("FoodDetailsTenantView_G", currentdateParameter);
        }
    
        public virtual ObjectResult<M_Weeks_G_Result> M_Weeks_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_Weeks_G_Result>("M_Weeks_G");
        }
    
        public virtual ObjectResult<FoodDetailsEdit_G_Result> FoodDetailsEdit_G(Nullable<int> yearId, Nullable<int> weekId)
        {
            var yearIdParameter = yearId.HasValue ?
                new ObjectParameter("YearId", yearId) :
                new ObjectParameter("YearId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("WeekId", weekId) :
                new ObjectParameter("WeekId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FoodDetailsEdit_G_Result>("FoodDetailsEdit_G", yearIdParameter, weekIdParameter);
        }
    
        public virtual ObjectResult<FoodDetailsView_G_Result> FoodDetailsView_G(Nullable<int> yearId, Nullable<int> weekId)
        {
            var yearIdParameter = yearId.HasValue ?
                new ObjectParameter("YearId", yearId) :
                new ObjectParameter("YearId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("WeekId", weekId) :
                new ObjectParameter("WeekId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FoodDetailsView_G_Result>("FoodDetailsView_G", yearIdParameter, weekIdParameter);
        }
    
        public virtual ObjectResult<FoodDetailsList_G_Result> FoodDetailsList_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FoodDetailsList_G_Result>("FoodDetailsList_G");
        }
    
        public virtual int RequestForm_CRUD(Nullable<int> requestId, Nullable<int> reportTypeID, Nullable<int> enterpriseID, string topic, Nullable<int> categoryId, Nullable<int> subCategoryId, string contactPersonName, string mobileNo, string emailId, Nullable<int> severityId, string uploadPath, string requestDescription, Nullable<int> createdBy, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter reqID, ObjectParameter outError)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            var reportTypeIDParameter = reportTypeID.HasValue ?
                new ObjectParameter("ReportTypeID", reportTypeID) :
                new ObjectParameter("ReportTypeID", typeof(int));
    
            var enterpriseIDParameter = enterpriseID.HasValue ?
                new ObjectParameter("EnterpriseID", enterpriseID) :
                new ObjectParameter("EnterpriseID", typeof(int));
    
            var topicParameter = topic != null ?
                new ObjectParameter("Topic", topic) :
                new ObjectParameter("Topic", typeof(string));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("SubCategoryId", subCategoryId) :
                new ObjectParameter("SubCategoryId", typeof(int));
    
            var contactPersonNameParameter = contactPersonName != null ?
                new ObjectParameter("ContactPersonName", contactPersonName) :
                new ObjectParameter("ContactPersonName", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var severityIdParameter = severityId.HasValue ?
                new ObjectParameter("SeverityId", severityId) :
                new ObjectParameter("SeverityId", typeof(int));
    
            var uploadPathParameter = uploadPath != null ?
                new ObjectParameter("UploadPath", uploadPath) :
                new ObjectParameter("UploadPath", typeof(string));
    
            var requestDescriptionParameter = requestDescription != null ?
                new ObjectParameter("RequestDescription", requestDescription) :
                new ObjectParameter("RequestDescription", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RequestForm_CRUD", requestIdParameter, reportTypeIDParameter, enterpriseIDParameter, topicParameter, categoryIdParameter, subCategoryIdParameter, contactPersonNameParameter, mobileNoParameter, emailIdParameter, severityIdParameter, uploadPathParameter, requestDescriptionParameter, createdByParameter, isActiveParameter, flagParameter, reqID, outError);
        }
    
        public virtual ObjectResult<Request_Email_AdminAllocation_G_Result> Request_Email_AdminAllocation_G(Nullable<int> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Request_Email_AdminAllocation_G_Result>("Request_Email_AdminAllocation_G", requestIdParameter);
        }
    
        public virtual ObjectResult<Eservice_Report_Result> Eservice_Report(Nullable<int> reportType, Nullable<int> requestStatus, Nullable<int> enterprise, Nullable<int> category, Nullable<int> subCategory, Nullable<int> severity, string topic, string requestDescription, string contactPersonName, string emailId, Nullable<System.DateTime> createddate, Nullable<System.DateTime> createddate2)
        {
            var reportTypeParameter = reportType.HasValue ?
                new ObjectParameter("ReportType", reportType) :
                new ObjectParameter("ReportType", typeof(int));
    
            var requestStatusParameter = requestStatus.HasValue ?
                new ObjectParameter("RequestStatus", requestStatus) :
                new ObjectParameter("RequestStatus", typeof(int));
    
            var enterpriseParameter = enterprise.HasValue ?
                new ObjectParameter("Enterprise", enterprise) :
                new ObjectParameter("Enterprise", typeof(int));
    
            var categoryParameter = category.HasValue ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(int));
    
            var subCategoryParameter = subCategory.HasValue ?
                new ObjectParameter("SubCategory", subCategory) :
                new ObjectParameter("SubCategory", typeof(int));
    
            var severityParameter = severity.HasValue ?
                new ObjectParameter("Severity", severity) :
                new ObjectParameter("Severity", typeof(int));
    
            var topicParameter = topic != null ?
                new ObjectParameter("Topic", topic) :
                new ObjectParameter("Topic", typeof(string));
    
            var requestDescriptionParameter = requestDescription != null ?
                new ObjectParameter("RequestDescription", requestDescription) :
                new ObjectParameter("RequestDescription", typeof(string));
    
            var contactPersonNameParameter = contactPersonName != null ?
                new ObjectParameter("ContactPersonName", contactPersonName) :
                new ObjectParameter("ContactPersonName", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var createddateParameter = createddate.HasValue ?
                new ObjectParameter("Createddate", createddate) :
                new ObjectParameter("Createddate", typeof(System.DateTime));
    
            var createddate2Parameter = createddate2.HasValue ?
                new ObjectParameter("Createddate2", createddate2) :
                new ObjectParameter("Createddate2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Eservice_Report_Result>("Eservice_Report", reportTypeParameter, requestStatusParameter, enterpriseParameter, categoryParameter, subCategoryParameter, severityParameter, topicParameter, requestDescriptionParameter, contactPersonNameParameter, emailIdParameter, createddateParameter, createddate2Parameter);
        }
    }
}
