//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CategorySubCategory
    {
        public int CategoryID { get; set; }
        public Nullable<byte> RequestTypeId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool IsActive { get; set; }
        public byte OrganizationId { get; set; }
    }
}
