//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FoodDetails_RTD
    {
        public int FDId { get; set; }
        public int WeekId { get; set; }
        public Nullable<System.DateTime> Monday_Date { get; set; }
        public string Monday_BF { get; set; }
        public string Monday_L { get; set; }
        public string Monday_D { get; set; }
        public Nullable<System.DateTime> Tuesday_Date { get; set; }
        public string Tuesday_BF { get; set; }
        public string Tuesday_L { get; set; }
        public string Tuesday_D { get; set; }
        public Nullable<System.DateTime> Wednesday_Date { get; set; }
        public string Wednesday_BF { get; set; }
        public string Wednesday_L { get; set; }
        public string Wednesday_D { get; set; }
        public Nullable<System.DateTime> Thursday_Date { get; set; }
        public string Thursday_BF { get; set; }
        public string Thursday_L { get; set; }
        public string Thursday_D { get; set; }
        public Nullable<System.DateTime> Friday_Date { get; set; }
        public string Friday_BF { get; set; }
        public string Friday_L { get; set; }
        public string Friday_D { get; set; }
        public Nullable<System.DateTime> Saturday_Date { get; set; }
        public string Saturday_BF { get; set; }
        public string Saturday_L { get; set; }
        public string Saturday_D { get; set; }
        public Nullable<System.DateTime> Sunday_Date { get; set; }
        public string Sunday_BF { get; set; }
        public string Sunday_L { get; set; }
        public string Sunday_D { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
