//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MeterDetails_RTD
    {
        public int MId { get; set; }
        public int YearId { get; set; }
        public int MonthId { get; set; }
        public int CategoryId { get; set; }
        public int SubcategoryId { get; set; }
        public decimal MeterReading { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool IsActive { get; set; }
    }
}
