//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_QuestionPollOption
    {
        public int PollOptionId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string PollName { get; set; }
        public Nullable<int> QuestionTypeId { get; set; }
        public Nullable<int> EditableTypeId { get; set; }
        public Nullable<int> TotalNoOfRating { get; set; }
        public Nullable<int> StartName { get; set; }
        public Nullable<int> EndName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
