//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_Request_history
    {
        public int AllocationId { get; set; }
        public int RequestId { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public int RequestStatusID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<System.DateTime> Commitementdate { get; set; }
        public Nullable<System.DateTime> EscalateOndate { get; set; }
        public string EscLevel1EmailId { get; set; }
        public string EscLevel2EmailId { get; set; }
        public string RequestComments { get; set; }
        public string UploadPath { get; set; }
        public Nullable<int> AllocatedTo { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool IsActive { get; set; }
        public string AllocatorUploadPath { get; set; }
        public string DepartmentUploadPath { get; set; }
    }
}
