//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyAlert
    {
        public int NotifyId { get; set; }
        public string NotifyText { get; set; }
        public int EnterpriseID { get; set; }
        public int SendToId { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public bool IsActive { get; set; }
    }
}
